# Analysis Example 4
# Checking for drop in Fenix DAU mid March
# https://docs.google.com/document/d/1umr5P35s4WM2zULyfNoBH_QrGubT9r89QeIuhE14Lzg/edit#
[analysis_profile]
name="Fenix DAU"

[analysis_profile.dataset]
metric_name="dau"
# this will have to specify the query template
table_name="active_user_aggregates"
app_name="Fenix"  # this is very specific

[analysis_profile.percent_change]
contrib_to_overall_change_threshold_percent = 1
dimensions=[
            "region_name",
            "subregion_name",
            "country",
]
sort_by=[
            "contrib_to_overall_change",
            "percent_change",
            "change_to_contrib",
            "percent_significance",
]

[notification]
[notification.report]
template = "report_version2.html.j2"

[notification.slack]
channel = "#overwatch-mvp"
message = "Fenix DAU"
